prefix error messages with "Error:"

diff --git a/mips_subroutine b/mips_subroutine
--- a/mips_subroutine
+++ b/mips_subroutine
@@ -953,26 +953,26 @@ SUB_NAME=$(basename ${SUB_NAME})
 
 # Command line related error checking
 [ ${SUB_NAME} != "main" ] || 
-     { echo "File name cannot be \"main.${LANG_EXT}\"." ; exit 1; }
+     { echo "Error: File name cannot be \"main.${LANG_EXT}\"." ; exit 1; }
 
 [ -f ${SUB_NAME_FILE} ] || 
-     { echo "File \"${SUB_NAME_FILE}\" does not exist." ; exit 1 ; }
+     { echo "Error: File \"${SUB_NAME_FILE}\" does not exist." ; exit 1 ; }
 
 if [[ ${VERSION} == "mips" ]] ; then 
   grep -q "${SUB_NAME}:" ${SUB_NAME_FILE}  || 
-       { echo "Subroutine $SUB_NAME not defined" ; exit 1; }
+       { echo "Error: Subroutine $SUB_NAME not defined" ; exit 1; }
   grep -q "\.globl *${SUB_NAME}" ${SUB_NAME_FILE}  || 
-       { echo "Subroutine $SUB_NAME not defined .globl" ; exit 1; }
+       { echo "Warning: Subroutine $SUB_NAME not defined .globl" ; }
 fi
 
 if [[ ${VERSION} == "java" ]] ; then 
   grep -q "public  *static  *int  *${SUB_NAME} *(" ${SUB_NAME_FILE}  || 
-       { echo "Subroutine $SUB_NAME not declared \"public static int\"." ; exit 1; }
+       { echo "Error: Subroutine $SUB_NAME not declared \"public static int\"." ; exit 1; }
 fi
 
 if [[ ${VERSION} == "c" ]] ; then 
   grep -q "${SUB_NAME}:" ${SUB_NAME_FILE}  || 
-       { echo "Subroutine $SUB_NAME not defined." ; exit 1; }
+       { echo "Error: Subroutine $SUB_NAME not defined." ; exit 1; }
 fi
 
 
