introduce notion of SUB_NAME_FILE

diff --git a/mips_subroutine b/mips_subroutine
--- a/mips_subroutine
+++ b/mips_subroutine
@@ -72,6 +72,7 @@ fi
 # ENVIRONMENT VARABLE DESCRIPTONS
 
 SUB_NAME=""                # The name of the subroutine to be executed
+SUB_NAME_FILE=""
 SUB_CALL=""                # The actual subroutine call, e.g., sub(1, 2, 3)
 
 SUB_ARGS_TEXT=""           # A set of arrays to represent the text, type, and value
@@ -621,6 +622,7 @@ function post_process () {
   fi
 
 
+  #  Return value is a problem sometimes, this should be done conditionally
   pretty_print_output "${SUB_RETURN_LINE}"
 
 
@@ -747,11 +749,29 @@ DUMP_REGISTERS="${DUMP_REG_LIST} ${DUMP_T_REGS} ${DUMP_V_REGS} ${DUMP_X_REGISTER
 eval "SUB_NAME=\${${OPTIND}}"
 shift ${OPTIND}
 
+
+# # Note that you must run the command in the current working directory of the files
+#
+SUB_NAME_FILE="${SUB_NAME}.s"
+SUB_NAME=$(basename ${SUB_NAME})
+
+# Command line related error checking
+[ $SUB_NAME != "main" ] || 
+     { echo "File name cannot be \"main.s\"." ; exit 1; }
+
+[ -f ${SUB_NAME_FILE} ] || 
+     { echo "File \"${SUB_NAME_FILE}\" does not exist." ; exit 1 ; }
+
+grep -q "${SUB_NAME}:" ${SUB_NAME_FILE}  || 
+     { echo "Subroutine $SUB_NAME not defined." ; exit 1; }
+
+
+
 SUB_ARGS_TEXT=( "$@" )
 
 
 # Determine the text, value, and type of each subroutine
-# arguments, and convert the string to the appropriate value
+# argument, and convert the string to the appropriate value
 for ((i=0; i < ${#SUB_ARGS_TEXT[@]}; i++)) ; do
   _type="string"
   _value=${SUB_ARGS_TEXT[$i]}
@@ -804,14 +824,6 @@ SUB_CALL=$(sub_routine_call)
 
 
 
-# Command line related error checking
-[ -f ${SUB_NAME}.s ] || 
-     { echo "File ${SUB_NAME}.s does not exist." ; exit 1 ; }
-[ $SUB_NAME != "main" ] || 
-     { echo "File name cannot be \"main.s\"." ; exit 1; }
-grep -q "${SUB_NAME}:" ${SUB_NAME}.s  || 
-     { echo "Subroutine $SUB_NAME not defined." ; exit 1; }
-
 
 # MARS is the execution hog... 
 # No value in checking for assembly before building the boot file
@@ -829,7 +841,7 @@ build_boot_file
 #  ae1 is needed in the case there is a linkage error.
 #  10000 is the max number of instructions to execute to prevent infinite loops
 ${MARS} 10000 nc sm ae2 se1 p ${DUMP_REGISTERS} \
-     ${BOOT_FILE} ${SUB_NAME}.s > ${OUTPUT_FILE} 2>/dev/null
+     ${BOOT_FILE} ${SUB_NAME_FILE} > ${OUTPUT_FILE} 2>/dev/null
 if [[ $? == 2 ]] ; then 
    sed "s|$PWD/||" ${OUTPUT_FILE}
    exit 1; 
