added ability to have -L {oad}, "'1"

diff --git a/mips_subroutine b/mips_subroutine
--- a/mips_subroutine
+++ b/mips_subroutine
@@ -129,7 +129,8 @@ fi
 # ENVIRONMENT VARABLE DESCRIPTONS
 
 SUB_NAME=""                # The name of the subroutine to be executed
-SUB_NAME_FILE=""
+SUB_NAME_FILE=""           # The default name of the file containing $SUB_NAME
+LOAD_FILES=""              # The list of files to be load
 SUB_CALL=""                # The actual subroutine call, e.g., sub(1, 2, 3)
 
 SUB_ARGS_TEXT=""           # A set of arrays to represent the text, type, and value
@@ -259,7 +260,7 @@ class ${SUB_NAME} {
 
 EOF
 
-cat ${SUB_NAME_FILE}
+cat ${LOAD_FILES}
 
 cat <<-EOF
 
@@ -798,7 +799,7 @@ execute_mips () {
   #  - se1: simulation run: error 1, if linkage error.
   #  - ae2: assemble run: error 1, if syntax error.
   ${MARS} 10000 nc sm se1 ae1 ${DUMP_REGISTERS} \
-       ${BOOTSTRAP_FILE} ${SUB_NAME_FILE} > ${OUTPUT_FILE} 2>&1
+       ${BOOTSTRAP_FILE} ${LOAD_FILES} > ${OUTPUT_FILE} 2>&1
 
   return $?
 }
@@ -946,7 +947,7 @@ while getopts hL:ASsr:R:tv option ; do
         h)  usage_full
             exit 1
             ;;
-        L)  LINK_FILE=${OPTARG}
+        L)  LOAD_FILES="${LOAD_FILES} ${OPTARG}"
             ;;
         A)  ARG_STRUCTURE="array" ;;
         R)  SUB_RETURN_ARRAY="FALSE"
@@ -986,7 +987,7 @@ shift ${OPTIND}
 # # Note that you must run the command in the current working directory of the files
 #
 SUB_NAME_FILE="${SUB_NAME}.${LANG_EXT}"
-[[ -n "${LINK_FILE}" ]] && SUB_NAME_FILE=${LINK_FILE}
+[[ -z "${LOAD_FILES}" ]] && LOAD_FILES=${SUB_NAME_FILE}
 
 
 SUB_NAME=$(basename ${SUB_NAME})
@@ -995,23 +996,25 @@ SUB_NAME=$(basename ${SUB_NAME})
 [ ${SUB_NAME} != "main" ] || 
      { echo "Error: File name cannot be \"main.${LANG_EXT}\"." ; exit 1; }
 
-[ -f ${SUB_NAME_FILE} ] || 
-     { echo "Error: File \"${SUB_NAME_FILE}\" does not exist." ; exit 1 ; }
+for i in ${LOAD_FILES} ; do
+  [ -f ${i} ] || 
+     { echo "Error: File \"${i}\" does not exist." ; exit 1 ; }
+done
 
 if [[ ${VERSION} == "mips" ]] ; then 
-  grep -q "${SUB_NAME}:" ${SUB_NAME_FILE}  || 
+  grep -q "${SUB_NAME}:" ${LOAD_FILES}  || 
        { echo "Error: Subroutine $SUB_NAME not defined" ; exit 1; }
-  grep -q "\.globl *${SUB_NAME}" ${SUB_NAME_FILE}  || 
+  grep -q "\.globl *${SUB_NAME}" ${LOAD_FILES}  || 
        { echo "Warning: Subroutine $SUB_NAME not defined .globl" ; }
 fi
 
 if [[ ${VERSION} == "java" ]] ; then 
-  grep -q "public  *static  *int  *${SUB_NAME} *(" ${SUB_NAME_FILE}  || 
-       { echo "Error: Subroutine $SUB_NAME not declared \"public static int\"." ; exit 1; }
+  grep -q "public  *static  *int  *${SUB_NAME} *(" ${LOAD_FILES}  || 
+       { echo "Error: Subroutine $SUB_NAME not declared as \"public static int\"." ; exit 1; }
 fi
 
 if [[ ${VERSION} == "c" ]] ; then 
-  grep -q "${SUB_NAME}:" ${SUB_NAME_FILE}  || 
+  grep -q "${SUB_NAME}:" ${LOAD_FILES}  || 
        { echo "Error: Subroutine $SUB_NAME not defined." ; exit 1; }
 fi
 
@@ -1026,46 +1029,57 @@ function process_subcommand_args () {
     _type="string"
     _value=${SUB_ARGS_TEXT[$i]}
 
-    # Handles ASCII chars
-    egrep -q "^.$" <<< ${SUB_ARGS_TEXT[$i]} &&
-          _type="char"
-    egrep -q "^\\.$" <<< ${SUB_ARGS_TEXT[$i]} &&
-          _type="char"
+    # The following test SHOULD be mutual exclusive
 
-    egrep -q "^[+-]?[0-9]+\.[0-9]+$" <<< ${SUB_ARGS_TEXT[$i]} &&
+    # Handles ASCII chars
+    egrep -q "^[^0-9]$" <<< "${SUB_ARGS_TEXT[$i]}" &&
+          _type="char" 
+    egrep -q "^\\\\[abcfnrtv]$" <<< "${SUB_ARGS_TEXT[$i]}" &&
+          _type="char" 
+    egrep -q "^\\\\\\$" <<< "${SUB_ARGS_TEXT[$i]}" &&
+          _type="char"  &&
+          _value="\\${SUB_ARGS_TEXT[$i]}"
+    egrep -q "^'.$" <<< ${SUB_ARGS_TEXT[$i]} && {
+          _type="char"
+          _value=${SUB_ARGS_TEXT[$i]:1:1}
+    }
+
+
+    # Handles doubles
+    egrep -q "^[+-]?[0-9]+\.[0-9]+$" <<< "${SUB_ARGS_TEXT[$i]}" &&
           _type="double"
 
     # Handles based numbers
-    egrep -q "^[+-]?[1-9][0-9]*#[ 0-9]+$" <<< ${SUB_ARGS_TEXT[$i]} && {
+    egrep -q "^[+-]?[1-9][0-9]*#[ 0-9]+$" <<< "${SUB_ARGS_TEXT[$i]}" && {
            # Note: does not prevent 1#, nor prevent digits outside the range
            _type="integer" 
-           _value=$(( $(sed -e 's/ //g' <<< ${SUB_ARGS_TEXT[$i]} ) ))
+           _value=$(( $(sed -e 's/ //g' <<< "${SUB_ARGS_TEXT[$i]}" ) ))
     }
 
     # Handles binary
-    egrep -q "^[+-]?0[bB][ 01]+$" <<< ${SUB_ARGS_TEXT[$i]} && {
+    egrep -q "^[+-]?0[bB][ 01]+$" <<< "${SUB_ARGS_TEXT[$i]}" && {
            _type="integer" 
-           _value=$(( $(sed -e 's/0[bB]/2#/' -e 's/ //g' <<< ${SUB_ARGS_TEXT[$i]} ) ))
+           _value=$(( $(sed -e 's/0[bB]/2#/' -e 's/ //g' <<< "${SUB_ARGS_TEXT[$i]}" ) ))
     }
 
 
     # Handles decimal.
-    egrep -q "^[+-]?[0-9][ 0-9]*$" <<< ${SUB_ARGS_TEXT[$i]} && {
+    egrep -q "^[+-]?[0-9][ 0-9]*$" <<< "${SUB_ARGS_TEXT[$i]}" && {
            _type="integer" 
-           _value=$(( $(sed -e 's/ //g' <<< ${SUB_ARGS_TEXT[$i]} ) ))
+           _value=$(( $(sed -e 's/ //g' <<< "${SUB_ARGS_TEXT[$i]}" ) ))
     }
 
     # Handles octal .
-    egrep -q "^[+-]?0[o]?[ 0-7]+$" <<< ${SUB_ARGS_TEXT[$i]} && {
+    egrep -q "^[+-]?0[o]?[ 0-7]+$" <<< "${SUB_ARGS_TEXT[$i]}" && {
            _type="integer" 
-           _octal_value=$(sed -e 's/[oO]//' -e 's/ //g' <<< ${SUB_ARGS_TEXT[$i]} )
+           _octal_value=$(sed -e 's/[oO]//' -e 's/ //g' <<< "${SUB_ARGS_TEXT[$i]}" )
            _value=$(( _octal_value ))
     }
 
     # Handles hexadecimal
-    egrep -q "^[+-]?0[xX]?[ 0-9A-Fa-f]+$" <<< ${SUB_ARGS_TEXT[$i]} && {
+    egrep -q "^[+-]?0[xX]?[ 0-9A-Fa-f]+$" <<< "${SUB_ARGS_TEXT[$i]}" && {
            _type="integer" 
-           _value=$(( $(sed -e 's/ //g' <<< ${SUB_ARGS_TEXT[$i]} ) ))
+           _value=$(( $(sed -e 's/ //g' <<< "${SUB_ARGS_TEXT[$i]}" ) ))
     }
 
     SUB_ARGS_TYPES[${i}]=$_type
